# Generated by Django 5.0.1 on 2024-03-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter the musicians first name', max_length=50)),
                ('last_name', models.CharField(help_text='Enter the musicians last name', max_length=50)),
                ('email', models.EmailField(help_text='Enter the musicians email address', max_length=254)),
                ('phone', models.CharField(help_text='Enter the musicians phone number', max_length=11)),
                ('instrument_type', models.CharField(help_text='Enter the instrument type', max_length=100)),
            ],
        ),
    ]
